package io.github.sifisofakude.core.bytesmith

import java.io.File

import io.github.sifisofakude.filesystem.*

/**
 * Default implementation of [ICompilationListener].
 *
 * This listener provides a simple mechanism for handling compiler
 * output by:
 *
 * - Printing compilation errors and warnings
 * - Tracking whether compilation errors occurred
 * - Writing generated class files to an output directory
 *
 * Generated classes are written using the configured
 * [FileSystemUtil], allowing output to be stored on different
 * filesystem implementations such as:
 *
 * - JVM filesystems
 * - Android Storage Access Framework (SAF)
 * - Custom filesystem implementations
 *
 * If no output directory is explicitly configured, the listener
 * attempts to use the current directory reported by the configured
 * filesystem.
 *
 * This implementation is intended to be suitable for command-line
 * tools and simple build systems while remaining extensible through
 * inheritance.
 */
open class DefaultCompilationListener : ICompilationListener  {
	/**
	 * Directory where compiled class files will be written.
	 *
	 * If not configured explicitly, the filesystem's current directory
	 * will be used when the first class is emitted.
	 */
  private var outputDir: String? = null

  /**
   * Filesystem used for output operations.
   */
  private var fs: FileSystemUtil? = null

  /**
   * Indicates whether at least one compilation error has been reported.
   */
  private var hasError = false

	/**
	 * Sets the directory where compiled class files will be written.
	 *
	 * @param outputDir destination directory
	 */
  fun setOutputDirectory(outputDir: String) {
    this.outputDir = outputDir
  }

	/**
	 * Sets the filesystem used for compiler output.
	 *
	 * The filesystem is responsible for directory creation,
	 * file creation, and writing generated bytecode.
	 *
	 * @param fs filesystem implementation
	 */
  fun setFileSystem(fs: FileSystemUtil) {
    this.fs = fs
  }

	/**
	 * Returns whether compilation errors have been reported.
	 *
	 * Warnings do not affect this value.
	 *
	 * @return true if one or more errors occurred
	 */
  override fun hasErrors(): Boolean = hasError

  /**
   * Receives a compilation problem.
   *
   * Errors are recorded internally and all problems are printed
   * using [CompilationProblem.printMessage].
   *
   * @param problem reported compilation problem
   */
  override fun onProblem(problem: CompilationProblem) {
  	if(problem.severity == Severity.ERROR)	{
  		hasError = true
  	}
    problem.printMessage()
  }

	/**
	 * Writes a compiled class to the configured output directory.
	 *
	 * Parent directories are created automatically when necessary.
	 *
	 * The resulting file path is constructed from the configured
	 * output directory and the class file name supplied by
	 * [CompiledClass].
	 *
	 * Example:
	 *
	 * ```text
	 * output/
	 * └── com/
	 *     └── example/
	 *         └── Main.class
	 * ```
	 *
	 * Since output is written through [FileSystemUtil], compiled
	 * classes can be emitted to traditional filesystem paths,
	 * Android SAF locations, or any custom filesystem implementation
	 * that supports output streams.
	 *
	 * @param compiledClass compiled class information and bytecode
	 *
	 * @throws IllegalStateException if no output directory can be
	 * determined from either [setOutputDirectory] or the configured
	 * filesystem
	 */
  override fun onClassCompiled(compiledClass: CompiledClass)  {
    if(outputDir == null) outputDir = fs?.getCurrentDirectory() 
      ?: throw IllegalStateException("Failed getting output directory for compiled classes")

    val path = "$outputDir${File.separator}${compiledClass.fileName}"
   	fs?.getParentFile(path)?.let	{
    	val parentPath = it
    	if(!(fs?.exists(parentPath) ?: false)) fs?.createDirectory(parentPath)
    }

    fs?.createFile(path)

    fs?.openOutputStream(path)?.use  { stream ->
      stream.write(compiledClass.bytes)
      stream.flush()
    }
  }
}
